import { Header } from '@/components/Header'
import { CartSidebar } from '@/components/cart/CartSidebar'
import { Providers } from '@/components/providers'
import '@/styles/globals.scss'

import { type ReactNode } from 'react'

export const metadata = {
  title: 'Cravo e Canela',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* @ts-expect-error -> Async Server Component */}
          <Header />

          {/* <CartSidebar /> */}
          {children}
        </Providers>
      </body>
    </html>
  )
}
